#ifndef __KSU_UAPI_FEATURE_H
#define __KSU_UAPI_FEATURE_H

enum ksu_feature_id {
    KSU_FEATURE_SU_COMPAT = 0,
    KSU_FEATURE_KERNEL_UMOUNT = 1,
    KSU_FEATURE_SULOG = 2,
    KSU_FEATURE_ADB_ROOT = 3,
    KSU_FEATURE_SELINUX_HIDE = 4,
    KSU_FEATURE_ORIGIN_VEIL = 5,
    KSU_FEATURE_SU_PROMPT = 6,
    KSU_FEATURE_SU_PROMPT_TIMEOUT = 7,
    KSU_FEATURE_SU_PROMPT_DEFAULT_ALLOW = 8,

    KSU_FEATURE_MAX
};

#endif
